name: flutter_planner
description: A Very Good Project created by Very Good CLI.
version: 0.0.2+2
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  activities_api:
    path: packages/activities/activities_api
  activities_repository:
    path: packages/activities/activities_repository
  authentication_api:
    path: packages/authentication/authentication_api
  authentication_repository:
    path: packages/authentication/authentication_repository 
  bloc: ^8.0.3
  bloc_concurrency: ^0.2.0
  dropdown_button2: ^1.6.2
  dynamic_timeline: ^0.1.2
  equatable: ^2.0.3
  flex_color_scheme: ^5.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^9.9.1
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  flutter_slidable: ^2.0.0
  go_router: ^5.0.5
  google_fonts: ^2.3.1
  hydrated_bloc: ^8.1.0
  intl: ^0.17.0
  isar: 3.0.0-dev.8
  isar_activities_api:
    path: packages/activities/isar_activities_api
  isar_authentication_api:
    path: packages/authentication/isar_authentication_api
  isar_flutter_libs: 3.0.0-dev.8   
  isar_routines_api:
    path: packages/routines/isar_routines_api
  isar_tasks_api:
    path: packages/tasks/isar_tasks_api
  loader_overlay: ^2.0.6
  local_reminders_api:
    path: packages/reminders/local_reminders_api
  path_provider: ^2.0.9
  reminders_api:
    path: packages/reminders/reminders_api
  reminders_repository:
    path: packages/reminders/reminders_repository
  routines_api:
    path: packages/routines/routines_api
  routines_repository:
    path: packages/routines/routines_repository
  stream_transform: ^2.0.0
  supabase_activities_api:
    path: packages/activities/supabase_activities_api
  supabase_authentication_api:
    path: packages/authentication/supabase_authentication_api
  supabase_flutter: ^0.3.1+3
  supabase_routines_api:
    path: packages/routines/supabase_routines_api
  supabase_tasks_api:
    path: packages/tasks/supabase_tasks_api
  table_calendar: ^3.0.5
  tasks_api:
    path: packages/tasks/tasks_api
  tasks_repository:
    path: packages/tasks/tasks_repository
  timezone: ^0.8.0
  url_launcher: ^6.0.20

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mockingjay: ^0.3.0
  mocktail: ^0.3.0
  msix: ^3.6.2
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true

  assets:
  - .env

msix_config:
  display_name: Flutter Planner
